#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.3.4.1"
dl http://www.oscommerce.com/files/oscommerce-${VERSION}.zip /usr/local/src

