#!/bin/sh -ex

DB_NAME=oscommerce
DB_USER=oscommerce
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/oscommerce

# unpack and set permissions
unzip $SRC/oscommerce-*.zip -d $SRC
mv $SRC/oscommerce-*/catalog $WEBROOT
mv $SRC/oscommerce-*/documentation.pdf $WEBROOT
rm -rf $SRC/oscommerce-*
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/pub
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/includes/work
chown -R www-data:www-data $WEBROOT/admin/backups
chown -R www-data:www-data $WEBROOT/admin/images/graphs
chown www-data:www-data $WEBROOT/includes/configure.php
chown www-data:www-data $WEBROOT/admin/includes/configure.php

# configure apache
a2dissite default
a2ensite oscommerce
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

