#!/bin/bash -e
# regenerate oscommerce mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/var/www/oscommerce/includes/configure.php
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$PASSWORD');|" $CONF

CONF=/var/www/oscommerce/admin/includes/configure.php
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$PASSWORD');|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=oscommerce --pass="$PASSWORD"

